word_list = [
    'шукаю маркетингове агентство',
    'шукаю лідген агентство',
    'потрібно маркетингове агентство',
    'потрібно лідген агентство',
    'потрібен лідген',
    'шукаю лідген агентство',
    'шукаю маркетолога',
    'шукаю таргетолога',
    'хто допоможе з клієнтами',
    'b2b клієнти',
    'потрібна допомога з клієнтами',
    'хто допоможе з продажами',
    'потрібна допомога з лідогенерацією',
    'потрібна лідогенерація',
    'надаємо послуги розробки',
    'ми команда розробників',
    'ми розробники',
    'ми команда it',
    'ми it',
    'ми digital',
    'ми crypto',
    'ми web',
    'ми девелоп',
    'ми команда аутсорс',
    'ми веб',
    'ми фінтех',
    'надаємо фінтех послуги',
    'ми saas',
    'надаємо послуги веб',
    'надаємо послуги it',
    'надаємо it послуги',
    'надаємо послуги digital',
    'надаємо digital послуги',
    'looking for a marketing agency',
    'looking for lidgen agency',
    'need marketing agency',
    'need a lidgen agency',
    'need a lidgen',
    'looking for lidgen agency',
    'looking for an agency',
    'looking for a marketer',
    'looking for a tagger',
    'need clients',
    'who will help with clients',
    'b2b clients',
    'need help with clients',
    'who can help with sales',
    'need help with lead generation',
    'need lead generation',
    'provide development services',
    'we are a development team',
    'we are developers',
    'we are the it team',
    'we are it'
    'we are digital',
    "we're crypto",
    'we web',
    'we are development',
    'we are outsourcing team',
    'we are fintech',
    'we provide fintech services',
    'we saas',
    'provide web services',
    'provide it services',
    'provide digital services',
    'ищу маркетинговое агентство',
    'ищу лидген агентство',
    'нужно маркетинговое агентство',
    'нужно лидген агентство',
    'нужен лидген',
    'ищу лидген агентство',
    'ищу маркетолога',
    'ищу таргетолога',
    'кто поможет с клиентами',
    'b2b клиенты',
    'нужна помощь с клиентами',
    'кто поможет с продажами',
    'нужна помощь с лидогенерацией',
    'нужна лидогенерация',
    'предоставляем услуги разработки',
    'мы команда разработчиков',
    'мы разработчики',
    'мы команда it',
    'мы it',
    'мы digital',
    'мы crypto',
    'мы web',
    'мы девелоп',
    'мы команда аутсорс',
    'мы веб',
    'мы финтех',
    'предоставляем финтех услуги',
    'мы saas',
    'предоставляем услуги веб',
    'предоставляем услуги it',
    'предоставляем it услуги',
    'предоставляем услуги digital',
    'предоставляем digital услуги',
    'я ceo',
    'потрібні ліди',
    'шукаю лідів',
    'цікава лідогенерація',
    'наші розробники',
    'потрібні контракти',
    'ми аутстаф',
    'ми аутсорс',
    'ми outstuff',
    'ми outsource',
    'потрібен upwork',
    'потрібен linkedin',
    'потрібні клієнти з linkedin',
    'потрібні клієнти з upwork',
    'потрібна лідогенерація linkedin',
    'потрібна лідогенерація upwork',
    'ми веб3',
    'ми web3',
    'ми blockchain development',
    'ми ai',
    'ми блокчейн',
    'looking for leads',
    'looking for leads',
    'interested in lead generation',
    'our developers',
    'need contracts',
    'we are outstaff',
    "we're outsourcing",
    "we're outstuff",
    "we're outsource",
    "we need sales",
    "we need upwork",
    "need linkedin",
    'need clients from linkedin',
    'need clients from upwork',
    'need linkedin lead generation',
    'need upwork lead generation',
    'we are crypto',
    'we are web3',
    "we're web3",
    'we are blockchain development',
    'we are ai',
    'we are blockchain',
    'нужны лиды',
    'ищу лидов',
    'интересна лидогенерация',
    'наши разработчики',
    'нужны контракты',
    'мы аутстаф',
    'мы аутсорс',
    'мы outstuff',
    'мы outsource',
    'нужен upwork',
    'нужен linkedin',
    'нужны клиенты с linkedin',
    'нужны клиенты с upwork',
    'нужна лидогенерация linkedin',
    'нужна лидогенерация  upwork',
    'мы крипто',
    'мы веб3',
    'мы web3',
    'мы blockchain development',
    'мы ai',
    'мы блокчейн',
    "я генеральний директор",
    'я ceo',
    'я фаундер',
    'я founder',
    'я coo',
    'я власник',
    'я директор',
    'я операційний директор',
    'лідогенерація',
    'лідген',
    'потрібен аутсорс',
    'i am the ceo',
    "i'm ceo",
    "i'm a founder",
    "i'm founder",
    "i'm coo",
    "i'm an owner",
    "i'm a director",
    "i'm the coo",
    'lead generation',
    'lidgen',
    'outsourcing',
    "i'm cto",
    'я генеральный директор',
    'я ceo',
    'я фаундер',
    'я founder',
    'я coo',
    'я владелец',
    'я директор',
    'я операционный директор',
    'я cto',
    'лидген',
    'нужен аутсорс'
]
